# Setup
title:        Vision Motion
tagline:      Mobile app that tracks motion and produces a graph.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       William Qin
  url:        http://williamqin.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

#Theme
theme: jekyll-theme-cayman
